[versions]
ackee-detekt-config = "1.0.0"
agp = "8.13.1"
detekt = "1.23.8"
dokka = "2.1.0"
gradle-testLogger = "4.0.0"
junit-bom = "6.0.1"
kotest = "6.0.4"
kotlin = "2.2.21"
kotlin-serialization = "1.9.0"
ksp = "2.3.2"
ktor = "3.3.2"
mavenPublish = "0.35.0"
okhttp-bom = "5.3.1"
retrofit = "3.0.0"

[libraries]
ackee-detekt-config-core = { module = "io.github.ackeecz:detekt-config-core", version.ref = "ackee-detekt-config" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp-bom" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver3" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

# Build-logic dependencies
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
mavenPublish-gradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-testLogger = { id = "com.adarshr.test-logger", version.ref = "gradle-testLogger" }
kotest-multiplatform = { id = "io.kotest", version.ref = "kotest" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

# Convention plugins
apythia-android-application = { id = "apythia.android.application" }
apythia-kotlin-jvm-library = { id = "apythia.kotlin.jvm.library" }
apythia-kotlin-jvm-librarywithtesting = { id = "apythia.kotlin.jvm.library-with-testing" }
apythia-kotlin-multiplatform-library = { id = "apythia.kotlin.multiplatform.library" }
apythia-kotlin-multiplatform-librarywithtesting = { id = "apythia.kotlin.multiplatform.library-with-testing" }
apythia-preflightchecks = { id = "apythia.preflightchecks" }
apythia-publishing = { id = "apythia.publishing" }
